export { default as ParentPortalDashboard } from './ParentPortalDashboard';
export { default as ChildDetailsPage } from './ChildDetailsPage';
export { default as ChildSchedulePage } from './ChildSchedulePage';
export { default as ParentChildrenPage } from './ParentChildrenPage';
export { default as ChildBehaviorPage } from './ChildBehaviorPage';
export { default as ChildHomeworkPage } from './ChildHomeworkPage';
export { default as ParentReportsPage } from './ParentReportsPage';
export { default as ParentMessagesPage } from './ParentMessagesPage';
export { default as ParentSettingsPage } from './ParentSettingsPage';
