#!/usr/bin/env python3
"""
Seed comprehensive data for demo teacher account (teacher@alnoor.edu.sa / teacher-1).
Populates: students, attendance, class_sessions, session_interactions, scores.

teacher-1 is assigned to all 9 classes in school-demo-001 (verified from
teacher_assignments collection: class-1أ, class-1ب, class-1ج, class-2أ,
class-2ب, class-2ج, class-3أ, class-3ب, class-3ج — all for sub-arabic).
The timetable_sessions (48 entries, Sun-Wed, 6 periods/day) are generated by
the AI timetable engine and already exist in the DB.

This script also validates that teacher_assignments and timetable_sessions
exist for teacher-1 before and after seeding.
"""
import asyncio
import uuid
import random
from datetime import datetime, timedelta, timezone

import sys as _sys
import os as _os
_sys.path.insert(0, _os.path.join(_os.path.dirname(_os.path.abspath(__file__)), ".."))
from scripts.seed_db_helper import get_seed_db

SCHOOL_ID = "school-demo-001"
TEACHER_ID = "teacher-1"

FIRST_NAMES_BOYS = [
    "محمد", "أحمد", "عبدالله", "خالد", "سعد", "فهد", "عمر", "ياسر", "نايف",
    "تركي", "سلطان", "عبدالرحمن", "إبراهيم", "ماجد", "بندر", "مشاري", "حمد",
    "ناصر", "علي", "صالح", "يوسف", "رائد", "طارق", "زياد", "وليد", "هاني",
    "سامي", "أنس", "مهند", "فيصل", "عادل", "باسل", "حسين", "جاسم", "رامي",
]
LAST_NAMES = [
    "القحطاني", "العتيبي", "الغامدي", "الزهراني", "الشمري", "المطيري",
    "الحربي", "الدوسري", "السبيعي", "العنزي", "الشهراني", "البلوي",
    "الجهني", "السلمي", "المالكي", "الرشيدي", "اليامي", "الخثعمي",
    "الأحمدي", "الحازمي", "العمري", "الفيفي", "النعمي", "الوادعي",
    "الثقفي", "البقمي", "الهاجري", "المحمدي", "السهلي", "العسيري",
]
FATHER_NAMES = [
    "سعد", "عبدالله", "محمد", "إبراهيم", "خالد", "ناصر", "فهد", "أحمد",
    "عمر", "علي", "صالح", "حمد", "سلطان", "عبدالرحمن", "ماجد", "تركي",
]

CLASS_INFO = {
    "class-1أ": {"name": "الصف الأول (أ)", "grade": "1", "grade_id": "grade-1"},
    "class-1ب": {"name": "الصف الأول (ب)", "grade": "1", "grade_id": "grade-1"},
    "class-1ج": {"name": "الصف الأول (ج)", "grade": "1", "grade_id": "grade-1"},
    "class-2أ": {"name": "الصف الثاني (أ)", "grade": "2", "grade_id": "grade-2"},
    "class-2ب": {"name": "الصف الثاني (ب)", "grade": "2", "grade_id": "grade-2"},
    "class-2ج": {"name": "الصف الثاني (ج)", "grade": "2", "grade_id": "grade-2"},
    "class-3أ": {"name": "الصف الثالث (أ)", "grade": "3", "grade_id": "grade-3"},
    "class-3ب": {"name": "الصف الثالث (ب)", "grade": "3", "grade_id": "grade-3"},
    "class-3ج": {"name": "الصف الثالث (ج)", "grade": "3", "grade_id": "grade-3"},
}

SUBJECT_ID = "sub-arabic"
NOW = datetime.now(timezone.utc)


def generate_student(class_id, class_info, index):
    sid = str(uuid.uuid4())
    first = random.choice(FIRST_NAMES_BOYS)
    father = random.choice(FATHER_NAMES)
    last = random.choice(LAST_NAMES)
    full_name = f"{first} {father} {last}"
    dob_year = 2019 - int(class_info["grade"])
    dob = datetime(dob_year, random.randint(1, 12), random.randint(1, 28))
    return {
        "id": sid,
        "user_id": sid,
        "full_name": full_name,
        "full_name_en": None,
        "email": f"stu-{sid[:8]}@alnoor.edu.sa",
        "phone": f"+96655{random.randint(1000000, 9999999)}",
        "school_id": SCHOOL_ID,
        "class_id": class_id,
        "class_name": class_info["name"],
        "grade_level": class_info["grade"],
        "student_number": f"STU-{uuid.uuid4().hex[:6].upper()}",
        "date_of_birth": dob.strftime("%Y-%m-%d"),
        "national_id": f"1{random.randint(100000000, 999999999)}",
        "gender": "male",
        "parent_phone": f"+96650{random.randint(1000000, 9999999)}",
        "parent_name": f"{random.choice(FATHER_NAMES)} {last}",
        "enrollment_date": "2025-09-01",
        "is_active": True,
        "created_at": NOW,
        "updated_at": NOW,
    }


def get_school_days(weeks_back=6):
    """Get Sun-Thu school days for the last N weeks."""
    days = []
    today = NOW.date()
    start = today - timedelta(days=weeks_back * 7)
    d = start
    while d <= today:
        if d.weekday() in (6, 0, 1, 2, 3):  # Sun=6, Mon=0, Tue=1, Wed=2, Thu=3
            days.append(d)
        d += timedelta(days=1)
    return days


def generate_attendance(student_id, class_id, school_days):
    records = []
    for day in school_days:
        r = random.random()
        if r < 0.88:
            status = "present"
        elif r < 0.95:
            status = "late"
        else:
            status = "absent"
        records.append({
            "id": str(uuid.uuid4()),
            "school_id": SCHOOL_ID,
            "tenant_id": SCHOOL_ID,
            "student_id": student_id,
            "class_id": class_id,
            "teacher_id": TEACHER_ID,
            "date": day.strftime("%Y-%m-%d"),
            "status": status,
            "created_at": datetime(day.year, day.month, day.day, 7, 0, tzinfo=timezone.utc),
        })
    return records


def generate_sessions_and_interactions(class_id, student_ids, school_days):
    sessions = []
    session_attendances = []
    interactions = []
    daily_scores = []
    ledger_entries = []

    session_days = school_days[-20:]

    for day in session_days:
        session_id = str(uuid.uuid4())
        start_dt = datetime(day.year, day.month, day.day, 8, 40, tzinfo=timezone.utc)
        end_dt = start_dt + timedelta(minutes=45)

        sessions.append({
            "id": session_id,
            "schedule_session_id": str(uuid.uuid4()),
            "teacher_id": TEACHER_ID,
            "class_id": class_id,
            "subject_id": SUBJECT_ID,
            "school_id": SCHOOL_ID,
            "date": day.strftime("%Y-%m-%d"),
            "start_time": start_dt,
            "end_time": end_dt,
            "status": "completed",
            "attendance_approved": True,
            "interaction_mode": random.choice(["review", "homework", "quiz"]),
            "created_at": start_dt,
        })

        present_students = random.sample(student_ids, k=max(int(len(student_ids) * 0.9), 1))
        for stu_id in student_ids:
            is_present = stu_id in present_students
            sa_status = "present" if is_present else random.choice(["absent", "late"])
            session_attendances.append({
                "id": str(uuid.uuid4()),
                "session_id": session_id,
                "student_id": stu_id,
                "status": sa_status,
                "is_draft": False,
                "recorded_by": TEACHER_ID,
                "recorded_at": start_dt,
                "approved_at": start_dt + timedelta(minutes=2),
                "approved_by": TEACHER_ID,
            })

            if is_present:
                daily_scores.append({
                    "id": str(uuid.uuid4()),
                    "date": day.strftime("%Y-%m-%d"),
                    "student_id": stu_id,
                    "school_id": SCHOOL_ID,
                    "score": 1,
                    "created_at": start_dt,
                })
                ledger_entries.append({
                    "id": str(uuid.uuid4()),
                    "student_id": stu_id,
                    "score_change": 1,
                    "category": "attendance",
                    "description": "حضور الحصة: present",
                    "date": day.strftime("%Y-%m-%d"),
                    "week": (day - timedelta(days=day.weekday())).strftime("%Y-%m-%d"),
                    "month": day.strftime("%Y-%m"),
                    "created_at": start_dt,
                })

        num_interactions = random.randint(4, 8)
        interacted = random.sample(present_students, k=min(num_interactions, len(present_students)))
        for stu_id in interacted:
            itype = random.choice(["question", "participation", "behaviour"])
            interaction = {
                "id": str(uuid.uuid4()),
                "session_id": session_id,
                "student_id": stu_id,
                "interaction_type": itype,
                "recorded_by": TEACHER_ID,
                "recorded_at": start_dt + timedelta(minutes=random.randint(5, 40)),
            }
            points = 0
            if itype == "question":
                result = random.choice(["correct", "wrong", "no_answer"])
                interaction["answer_result"] = result
                points = 5 if result == "correct" else (-2 if result == "wrong" else 0)
            elif itype == "participation":
                ptype = random.choice(["active", "initiative", "good_listening"])
                interaction["participation_type"] = ptype
                points = 2
            else:
                bcat = random.choice(["positive", "respect", "teamwork"])
                interaction["behaviour_category"] = bcat
                interaction["behaviour_type"] = "positive"
                points = 2

            interactions.append(interaction)

            if points != 0:
                daily_scores.append({
                    "id": str(uuid.uuid4()),
                    "date": day.strftime("%Y-%m-%d"),
                    "student_id": stu_id,
                    "score": points,
                    "created_at": interaction["recorded_at"],
                })
                ledger_entries.append({
                    "id": str(uuid.uuid4()),
                    "student_id": stu_id,
                    "score_change": points,
                    "category": itype,
                    "description": f"تفاعل: {itype}",
                    "date": day.strftime("%Y-%m-%d"),
                    "week": (day - timedelta(days=day.weekday())).strftime("%Y-%m-%d"),
                    "month": day.strftime("%Y-%m"),
                    "created_at": interaction["recorded_at"],
                })

    return sessions, session_attendances, interactions, daily_scores, ledger_entries


async def main():
    _seed_ctx = get_seed_db()

    db = await _seed_ctx.__aenter__()

    print("🧹 Cleaning old seeded data for school-demo-001...")
    class_ids = list(CLASS_INFO.keys())
    old_students = await db.students.find(
        {"school_id": SCHOOL_ID, "class_id": {"$in": class_ids}},
        {"id": 1}
    ).to_list(None)
    old_student_ids = [s["id"] for s in old_students]

    if old_student_ids:
        await db.students.delete_many({"id": {"$in": old_student_ids}})
        await db.attendance.delete_many({"student_id": {"$in": old_student_ids}})
        await db.session_attendance.delete_many({"student_id": {"$in": old_student_ids}})
        await db.session_interactions.delete_many({"student_id": {"$in": old_student_ids}})
        await db.student_daily_scores.delete_many({"student_id": {"$in": old_student_ids}})
        await db.student_score_ledger.delete_many({"student_id": {"$in": old_student_ids}})

    await db.class_sessions.delete_many({"teacher_id": TEACHER_ID, "status": "completed"})

    print("👤 Fixing teacher user record...")
    await db.users.update_one(
        {"email": "teacher@alnoor.edu.sa"},
        {"$set": {"teacher_id": "teacher-1", "tenant_id": SCHOOL_ID}}
    )

    print("🏫 Fixing class tenant_id fields...")
    for cid, info in CLASS_INFO.items():
        await db.classes.update_one(
            {"id": cid},
            {"$set": {"tenant_id": SCHOOL_ID, "school_id": SCHOOL_ID}}
        )

    print("👨‍🎓 Seeding students...")
    all_students = []
    class_student_map = {}
    students_per_class = 25
    for class_id, info in CLASS_INFO.items():
        class_students = [generate_student(class_id, info, i) for i in range(students_per_class)]
        all_students.extend(class_students)
        class_student_map[class_id] = [s["id"] for s in class_students]

    if all_students:
        await db.students.insert_many(all_students)
    print(f"   ✅ {len(all_students)} students across {len(CLASS_INFO)} classes")

    school_days = get_school_days(weeks_back=6)
    print(f"📅 School days (last 6 weeks): {len(school_days)} days")

    print("📋 Seeding attendance records...")
    all_attendance = []
    for student in all_students:
        all_attendance.extend(generate_attendance(student["id"], student["class_id"], school_days))
    if all_attendance:
        await db.attendance.insert_many(all_attendance)
    print(f"   ✅ {len(all_attendance)} attendance records")

    print("📚 Seeding class sessions + interactions...")
    all_sessions = []
    all_sa = []
    all_interactions = []
    all_scores = []
    all_ledger = []

    for class_id, student_ids in class_student_map.items():
        sess, sa, inter, scores, ledger = generate_sessions_and_interactions(
            class_id, student_ids, school_days
        )
        all_sessions.extend(sess)
        all_sa.extend(sa)
        all_interactions.extend(inter)
        all_scores.extend(scores)
        all_ledger.extend(ledger)

    if all_sessions:
        await db.class_sessions.insert_many(all_sessions)
    if all_sa:
        await db.session_attendance.insert_many(all_sa)
    if all_interactions:
        await db.session_interactions.insert_many(all_interactions)
    if all_scores:
        await db.student_daily_scores.insert_many(all_scores)
    if all_ledger:
        await db.student_score_ledger.insert_many(all_ledger)

    print(f"   ✅ {len(all_sessions)} sessions")
    print(f"   ✅ {len(all_sa)} session attendance records")
    print(f"   ✅ {len(all_interactions)} interactions")
    print(f"   ✅ {len(all_scores)} daily score entries")
    print(f"   ✅ {len(all_ledger)} ledger entries")

    print("\n🔍 Verification...")
    user = await db.users.find_one({"email": "teacher@alnoor.edu.sa"}, {"_id": 0, "teacher_id": 1, "tenant_id": 1})
    print(f"   User teacher_id: {user.get('teacher_id')}, tenant_id: {user.get('tenant_id')}")

    total_students = await db.students.count_documents({"school_id": SCHOOL_ID, "class_id": {"$in": class_ids}})
    print(f"   Total students in teacher-1 classes: {total_students}")

    total_att = await db.attendance.count_documents({"school_id": SCHOOL_ID, "teacher_id": TEACHER_ID})
    print(f"   Total attendance records: {total_att}")
    att_sample = await db.attendance.find_one({"school_id": SCHOOL_ID, "teacher_id": TEACHER_ID}, {"_id": 0})
    att_keys = sorted(att_sample.keys()) if att_sample else []
    print(f"   Attendance fields: {att_keys}")

    total_sessions = await db.class_sessions.count_documents({"teacher_id": TEACHER_ID, "status": "completed"})
    print(f"   Completed sessions: {total_sessions}")

    assignments = await db.teacher_assignments.count_documents({"teacher_id": TEACHER_ID})
    timetable = await db.timetable_sessions.count_documents({"teacher_id": TEACHER_ID})
    print(f"   Teacher assignments: {assignments}")
    print(f"   Timetable sessions: {timetable}")
    if assignments == 0:
        print("   ⚠️  WARNING: No teacher_assignments found — run AI timetable generator first")
    if timetable == 0:
        print("   ⚠️  WARNING: No timetable_sessions found — schedule page will be empty")

    print("\n✅ Demo teacher data seeding complete!")
if __name__ == "__main__":
    asyncio.run(main())
