"""add_generic_documents_table

Revision ID: 0ddc122c827a
Revises: 6ba4c4afaf24
Create Date: 2026-04-05 15:27:03.674216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0ddc122c827a'
down_revision: Union[str, Sequence[str], None] = '6ba4c4afaf24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generic_documents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('collection', sa.String(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_generic_docs_collection', 'generic_documents', ['collection'], unique=False)
    op.create_index(op.f('ix_generic_documents_collection'), 'generic_documents', ['collection'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_generic_documents_collection'), table_name='generic_documents')
    op.drop_index('idx_generic_docs_collection', table_name='generic_documents')
    op.drop_table('generic_documents')
    # ### end Alembic commands ###
