"""initial_schema_with_fk_relationships

Revision ID: 6ba4c4afaf24
Revises: 
Create Date: 2026-04-05 15:08:44.553926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6ba4c4afaf24'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('counters',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('educational_stages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name_ar', sa.String(), nullable=True),
    sa.Column('name_en', sa.String(), nullable=True),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schools',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('name_en', sa.String(), nullable=True),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('district', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('logo_url', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('school_type', sa.String(), nullable=True),
    sa.Column('stage', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('calendar_system', sa.String(), nullable=True),
    sa.Column('student_capacity', sa.Integer(), nullable=True),
    sa.Column('current_students', sa.Integer(), nullable=True),
    sa.Column('current_teachers', sa.Integer(), nullable=True),
    sa.Column('current_student_count', sa.Integer(), nullable=True),
    sa.Column('current_teacher_count', sa.Integer(), nullable=True),
    sa.Column('principal_id', sa.String(), nullable=True),
    sa.Column('principal_name', sa.String(), nullable=True),
    sa.Column('principal_email', sa.String(), nullable=True),
    sa.Column('principal_phone', sa.String(), nullable=True),
    sa.Column('configuration', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('location', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ministry_id', sa.String(), nullable=True),
    sa.Column('license_number', sa.String(), nullable=True),
    sa.Column('tenant_type', sa.String(), nullable=True),
    sa.Column('setup_completed', sa.Boolean(), nullable=True),
    sa.Column('setup_steps_completed', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('health_score', sa.Float(), nullable=True),
    sa.Column('last_health_check', sa.String(), nullable=True),
    sa.Column('subscription_start', sa.String(), nullable=True),
    sa.Column('subscription_end', sa.String(), nullable=True),
    sa.Column('trial_end', sa.String(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schools_city'), 'schools', ['city'], unique=False)
    op.create_index(op.f('ix_schools_code'), 'schools', ['code'], unique=True)
    op.create_index(op.f('ix_schools_status'), 'schools', ['status'], unique=False)
    op.create_table('skills_types',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name_ar', sa.String(), nullable=True),
    sa.Column('name_en', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skills_types_category'), 'skills_types', ['category'], unique=False)
    op.create_table('academic_years',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('school_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('name_en', sa.String(), nullable=True),
    sa.Column('start_date', sa.String(), nullable=True),
    sa.Column('end_date', sa.String(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_academic_years_school_id'), 'academic_years', ['school_id'], unique=False)
    op.create_table('ai_insights',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('school_id', sa.String(), nullable=True),
    sa.Column('entity_type', sa.String(), nullable=True),
    sa.Column('entity_id', sa.String(), nullable=True),
    sa.Column('insight_type', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('is_actionable', sa.Boolean(), nullable=True),
    sa.Column('is_dismissed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pg_ai_insights_entity_type', 'ai_insights', ['entity_type', 'entity_id'], unique=False)
    op.create_index('idx_pg_ai_insights_school_type', 'ai_insights', ['school_id', 'insight_type'], unique=False)
    op.create_index(op.f('ix_ai_insights_created_at'), 'ai_insights', ['created_at'], unique=False)
    op.create_index(op.f('ix_ai_insights_entity_type'), 'ai_insights', ['entity_type'], unique=False)
    op.create_index(op.f('ix_ai_insights_insight_type'), 'ai_insights', ['insight_type'], unique=False)
    op.create_index(op.f('ix_ai_insights_school_id'), 'ai_insights', ['school_id'], unique=False)
    op.create_table('behaviour_types',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=True),
    sa.Column('name_ar', sa.String(), nullable=True),
    sa.Column('name_en', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('default_severity', sa.String(), nullable=True),
    sa.Column('default_points', sa.Integer(), nullable=True),
    sa.Column('auto_escalate', sa.Boolean(), nullable=True),
    sa.Column('escalation_threshold', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_global', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grade_levels',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('school_id', sa.String(), nullable=True),
    sa.Column('name_ar', sa.String(), nullable=True),
    sa.Column('name_en', sa.String(), nullable=True),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('stage', sa.String(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hakim_insights',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('school_id', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('is_dismissed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pg_hakim_school_date', 'hakim_insights', ['school_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_hakim_insights_school_id'), 'hakim_insights', ['school_id'], unique=False)
    op.create_table('lookup_options',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value_ar', sa.String(), nullable=True),
    sa.Column('value_en', sa.String(), nullable=True),
    sa.Column('parent_key', sa.String(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('school_id', sa.String(), nullable=True),
    sa.Column('is_global', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pg_lookup_category_key', 'lookup_options', ['category', 'key'], unique=False)
    op.create_index(op.f('ix_lookup_options_category'), 'lookup_options', ['category'], unique=False)
    op.create_table('parents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('full_name_en', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('national_id', sa.String(), nullable=True),
    sa.Column('student_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('school_id', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parents_email'), 'parents', ['email'], unique=False)
    op.create_table('physical_classrooms',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('building', sa.String(), nullable=True),
    sa.Column('floor', sa.Integer(), nullable=True),
    sa.Column('room_type', sa.String(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('has_projector', sa.Boolean(), nullable=True),
    sa.Column('has_smartboard', sa.Boolean(), nullable=True),
    sa.Column('has_ac', sa.Boolean(), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('school_settings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('school_id', sa.String(), nullable=False),
    sa.Column('working_days', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('periods_per_day', sa.Integer(), nullable=True),
    sa.Column('period_duration', sa.Integer(), nullable=True),
    sa.Column('break_duration', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.String(), nullable=True),
    sa.Column('end_time', sa.String(), nullable=True),
    sa.Column('grading_system', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('calendar', sa.String(), nullable=True),
    sa.Column('notification_preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('custom_settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_school_settings_school_id'), 'school_settings', ['school_id'], unique=True)
    op.create_table('subjects',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('name_ar', sa.String(), nullable=True),
    sa.Column('name_en', sa.String(), nullable=True),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('school_id', sa.String(), nullable=True),
    sa.Column('tenant_id', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('default_periods_per_week', sa.Integer(), nullable=True),
    sa.Column('applicable_stages', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_global', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subjects_school_id'), 'subjects', ['school_id'], unique=False)
    op.create_table('teachers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('full_name_en', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('school_id', sa.String(), nullable=False),
    sa.Column('specialization', sa.String(), nullable=True),
    sa.Column('rank', sa.String(), nullable=True),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('qualification', sa.String(), nullable=True),
    sa.Column('years_of_experience', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('national_id', sa.String(), nullable=True),
    sa.Column('weekly_periods', sa.Integer(), nullable=True),
    sa.Column('max_daily_periods', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pg_teachers_school_active', 'teachers', ['school_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_teachers_email'), 'teachers', ['email'], unique=False)
    op.create_index(op.f('ix_teachers_school_id'), 'teachers', ['school_id'], unique=False)
    op.create_table('time_slots',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('school_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('name_en', sa.String(), nullable=True),
    sa.Column('start_time', sa.String(), nullable=False),
    sa.Column('end_time', sa.String(), nullable=False),
    sa.Column('slot_number', sa.Integer(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('is_break', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_time_slots_school_id'), 'time_slots', ['school_id'], unique=False)
    op.create_table('timetable_constraints',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('school_id', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('name_en', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_global', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('timetable_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('school_id', sa.String(), nullable=False),
    sa.Column('schedule_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sessions_created', sa.Integer(), nullable=True),
    sa.Column('conflicts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('warnings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('completed_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timetable_runs_school_id'), 'timetable_runs', ['school_id'], unique=False)
    op.create_table('timetables',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('school_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('name_en', sa.String(), nullable=True),
    sa.Column('academic_year', sa.String(), nullable=True),
    sa.Column('semester', sa.Integer(), nullable=True),
    sa.Column('effective_from', sa.String(), nullable=True),
    sa.Column('effective_to', sa.String(), nullable=True),
    sa.Column('working_days', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('total_sessions', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timetables_school_id'), 'timetables', ['school_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('national_id', sa.String(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('full_name_en', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=True),
    sa.Column('last_password_change', sa.String(), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=True),
    sa.Column('locked_until', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('linked_roles', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('preferred_language', sa.String(), nullable=True),
    sa.Column('preferred_theme', sa.String(), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('tenant_id', sa.String(), nullable=True),
    sa.Column('primary_tenant_id', sa.String(), nullable=True),
    sa.Column('has_generic_name', sa.Boolean(), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=True),
    sa.Column('phone_verified', sa.Boolean(), nullable=True),
    sa.Column('teacher_id', sa.String(), nullable=True),
    sa.Column('student_id', sa.String(), nullable=True),
    sa.Column('parent_id', sa.String(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('last_login', sa.String(), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('educational_department', sa.String(), nullable=True),
    sa.Column('school_name_ar', sa.String(), nullable=True),
    sa.Column('school_name_en', sa.String(), nullable=True),
    sa.Column('permissions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notification_settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['schools.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pg_users_role_tenant', 'users', ['role', 'tenant_id'], unique=False)
    op.create_index('idx_pg_users_tenant_active', 'users', ['tenant_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_table('academic_terms',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('school_id', sa.String(), nullable=False),
    sa.Column('academic_year_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('name_en', sa.String(), nullable=True),
    sa.Column('start_date', sa.String(), nullable=True),
    sa.Column('end_date', sa.String(), nullable=True),
    sa.Column('term_number', sa.Integer(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pg_terms_school_year', 'academic_terms', ['school_id', 'academic_year_id'], unique=False)
    op.create_index(op.f('ix_academic_terms_school_id'), 'academic_terms', ['school_id'], unique=False)
    op.create_table('approval_requests',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=True),
    sa.Column('entity_type', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('requested_by', sa.String(), nullable=True),
    sa.Column('requested_by_name', sa.String(), nullable=True),
    sa.Column('school_id', sa.String(), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reviewed_by', sa.String(), nullable=True),
    sa.Column('reviewed_at', sa.String(), nullable=True),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('school_id', sa.String(), nullable=True),
    sa.Column('tenant_id', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=True),
    sa.Column('entity_id', sa.String(), nullable=True),
    sa.Column('performed_by', sa.String(), nullable=True),
    sa.Column('actor_name', sa.String(), nullable=True),
    sa.Column('actor_role', sa.String(), nullable=True),
    sa.Column('target_id', sa.String(), nullable=True),
    sa.Column('target_type', sa.String(), nullable=True),
    sa.Column('previous_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('timestamp', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['performed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pg_audit_entity', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_index('idx_pg_audit_school_time', 'audit_logs', ['school_id', 'timestamp'], unique=False)
    op.create_index('idx_pg_audit_user_time', 'audit_logs', ['performed_by', 'timestamp'], unique=False)
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_performed_by'), 'audit_logs', ['performed_by'], unique=False)
    op.create_index(op.f('ix_audit_logs_school_id'), 'audit_logs', ['school_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_table('bulk_action_history',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('action_type', sa.String(), nullable=False),
    sa.Column('issue_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('field', sa.String(), nullable=True),
    sa.Column('old_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_value', sa.String(), nullable=True),
    sa.Column('performed_by', sa.String(), nullable=True),
    sa.Column('performed_by_name', sa.String(), nullable=True),
    sa.Column('performed_at', sa.String(), nullable=True),
    sa.Column('is_undone', sa.Boolean(), nullable=True),
    sa.Column('undone_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['performed_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pg_bulk_history_user_date', 'bulk_action_history', ['performed_by', 'performed_at'], unique=False)
    op.create_index(op.f('ix_bulk_action_history_performed_at'), 'bulk_action_history', ['performed_at'], unique=False)
    op.create_table('classes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('name_en', sa.String(), nullable=True),
    sa.Column('school_id', sa.String(), nullable=False),
    sa.Column('grade_id', sa.String(), nullable=True),
    sa.Column('grade_level', sa.String(), nullable=True),
    sa.Column('section', sa.String(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('current_count', sa.Integer(), nullable=True),
    sa.Column('current_students', sa.Integer(), nullable=True),
    sa.Column('homeroom_teacher_id', sa.String(), nullable=True),
    sa.Column('homeroom_teacher_name', sa.String(), nullable=True),
    sa.Column('classroom_id', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['homeroom_teacher_id'], ['teachers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pg_classes_school_active', 'classes', ['school_id', 'is_active'], unique=False)
    op.create_index('idx_pg_classes_school_grade', 'classes', ['school_id', 'grade_id'], unique=False)
    op.create_index(op.f('ix_classes_school_id'), 'classes', ['school_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('sender_id', sa.String(), nullable=True),
    sa.Column('recipient_id', sa.String(), nullable=True),
    sa.Column('school_id', sa.String(), nullable=True),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('read_at', sa.String(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pg_messages_recipient', 'messages', ['recipient_id', 'is_read'], unique=False)
    op.create_index('idx_pg_messages_sender', 'messages', ['sender_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_messages_recipient_id'), 'messages', ['recipient_id'], unique=False)
    op.create_index(op.f('ix_messages_sender_id'), 'messages', ['sender_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('read_at', sa.String(), nullable=True),
    sa.Column('action_url', sa.String(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['schools.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pg_notifications_tenant_date', 'notifications', ['tenant_id', 'created_at'], unique=False)
    op.create_index('idx_pg_notifications_user_read_date', 'notifications', ['user_id', 'is_read', 'created_at'], unique=False)
    op.create_index(op.f('ix_notifications_tenant_id'), 'notifications', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('platform_settings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platform_settings_type'), 'platform_settings', ['type'], unique=True)
    op.create_table('product_issues',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('issue_number', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('issue_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('ai_suggested_priority', sa.String(), nullable=True),
    sa.Column('section', sa.String(), nullable=True),
    sa.Column('page', sa.String(), nullable=True),
    sa.Column('employee_name', sa.String(), nullable=True),
    sa.Column('employee_id', sa.String(), nullable=True),
    sa.Column('account_type', sa.String(), nullable=True),
    sa.Column('current_behavior', sa.Text(), nullable=True),
    sa.Column('expected_behavior', sa.Text(), nullable=True),
    sa.Column('steps_to_reproduce', sa.Text(), nullable=True),
    sa.Column('reproducibility', sa.String(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_code', sa.String(), nullable=True),
    sa.Column('screen_area', sa.String(), nullable=True),
    sa.Column('affected_elements', sa.String(), nullable=True),
    sa.Column('user_journey', sa.Text(), nullable=True),
    sa.Column('pain_point', sa.Text(), nullable=True),
    sa.Column('load_time', sa.String(), nullable=True),
    sa.Column('affected_operation', sa.String(), nullable=True),
    sa.Column('content_location', sa.String(), nullable=True),
    sa.Column('content_type_field', sa.String(), nullable=True),
    sa.Column('use_case', sa.Text(), nullable=True),
    sa.Column('business_value', sa.Text(), nullable=True),
    sa.Column('improvement_area', sa.Text(), nullable=True),
    sa.Column('expected_impact', sa.Text(), nullable=True),
    sa.Column('affected_role', sa.String(), nullable=True),
    sa.Column('expected_access', sa.String(), nullable=True),
    sa.Column('workflow_name', sa.String(), nullable=True),
    sa.Column('broken_step', sa.String(), nullable=True),
    sa.Column('integration_name', sa.String(), nullable=True),
    sa.Column('api_endpoint', sa.String(), nullable=True),
    sa.Column('additional_details', sa.Text(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('device', sa.String(), nullable=True),
    sa.Column('browser', sa.String(), nullable=True),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('description', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('impact', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('technical', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('business', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('assignment', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ai', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('attachments', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('submission_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('visibility', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('system', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('assigned_team', sa.String(), nullable=True),
    sa.Column('assigned_to', sa.String(), nullable=True),
    sa.Column('assigned_to_name', sa.String(), nullable=True),
    sa.Column('assigned_at', sa.String(), nullable=True),
    sa.Column('hakim_analysis', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('generated_prompt', sa.Text(), nullable=True),
    sa.Column('duplicate_of', sa.String(), nullable=True),
    sa.Column('sla_deadline', sa.String(), nullable=True),
    sa.Column('sla_status', sa.String(), nullable=True),
    sa.Column('sla_warning_emitted', sa.Boolean(), nullable=True),
    sa.Column('feedback_requested', sa.Boolean(), nullable=True),
    sa.Column('feedback_response', sa.Text(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_by_name', sa.String(), nullable=True),
    sa.Column('created_by_role', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.Column('resolved_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['duplicate_of'], ['product_issues.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('issue_number')
    )
    op.create_index('idx_pg_issues_active_creator_date', 'product_issues', ['is_deleted', 'created_by', 'created_at'], unique=False)
    op.create_index('idx_pg_issues_active_status_date', 'product_issues', ['is_deleted', 'status', 'created_at'], unique=False)
    op.create_index('idx_pg_issues_created_by_date', 'product_issues', ['created_by', 'created_at'], unique=False)
    op.create_index('idx_pg_issues_status_priority_date', 'product_issues', ['status', 'priority', 'created_at'], unique=False)
    op.create_index('idx_pg_issues_status_team', 'product_issues', ['status', 'assigned_team'], unique=False)
    op.create_index(op.f('ix_product_issues_assigned_team'), 'product_issues', ['assigned_team'], unique=False)
    op.create_index(op.f('ix_product_issues_created_by'), 'product_issues', ['created_by'], unique=False)
    op.create_index(op.f('ix_product_issues_employee_name'), 'product_issues', ['employee_name'], unique=False)
    op.create_index(op.f('ix_product_issues_is_deleted'), 'product_issues', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_product_issues_issue_type'), 'product_issues', ['issue_type'], unique=False)
    op.create_index(op.f('ix_product_issues_priority'), 'product_issues', ['priority'], unique=False)
    op.create_index(op.f('ix_product_issues_section'), 'product_issues', ['section'], unique=False)
    op.create_index(op.f('ix_product_issues_status'), 'product_issues', ['status'], unique=False)
    op.create_table('registration_requests',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('school_name', sa.String(), nullable=True),
    sa.Column('school_id', sa.String(), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('reviewed_by', sa.String(), nullable=True),
    sa.Column('reviewed_at', sa.String(), nullable=True),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('payload_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('linked_entity_type', sa.String(), nullable=True),
    sa.Column('linked_entity_id', sa.String(), nullable=True),
    sa.Column('review_notes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('priority_field', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pg_requests_status_date', 'registration_requests', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_registration_requests_status'), 'registration_requests', ['status'], unique=False)
    op.create_table('session_event_log',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('performed_by', sa.String(), nullable=True),
    sa.Column('timestamp', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['performed_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pg_session_events_session_time', 'session_event_log', ['session_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_session_event_log_event_type'), 'session_event_log', ['event_type'], unique=False)
    op.create_index(op.f('ix_session_event_log_session_id'), 'session_event_log', ['session_id'], unique=False)
    op.create_table('approval_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('request_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('from_status', sa.String(), nullable=True),
    sa.Column('to_status', sa.String(), nullable=True),
    sa.Column('performed_by', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('timestamp', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['performed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['request_id'], ['approval_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pg_approval_events_request', 'approval_events', ['request_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_approval_events_request_id'), 'approval_events', ['request_id'], unique=False)
    op.create_table('assessments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('school_id', sa.String(), nullable=False),
    sa.Column('class_id', sa.String(), nullable=True),
    sa.Column('subject_id', sa.String(), nullable=True),
    sa.Column('teacher_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('name_en', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('max_score', sa.Float(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('due_date', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('grading_criteria', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pg_assessments_school_class', 'assessments', ['school_id', 'class_id'], unique=False)
    op.create_index(op.f('ix_assessments_class_id'), 'assessments', ['class_id'], unique=False)
    op.create_index(op.f('ix_assessments_school_id'), 'assessments', ['school_id'], unique=False)
    op.create_index(op.f('ix_assessments_teacher_id'), 'assessments', ['teacher_id'], unique=False)
    op.create_table('issue_activity_log',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('issue_id', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('field', sa.String(), nullable=True),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('performed_by', sa.String(), nullable=True),
    sa.Column('performed_by_name', sa.String(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('timestamp', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['issue_id'], ['product_issues.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['performed_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pg_activity_issue_time', 'issue_activity_log', ['issue_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_issue_activity_log_action'), 'issue_activity_log', ['action'], unique=False)
    op.create_index(op.f('ix_issue_activity_log_issue_id'), 'issue_activity_log', ['issue_id'], unique=False)
    op.create_index(op.f('ix_issue_activity_log_performed_by'), 'issue_activity_log', ['performed_by'], unique=False)
    op.create_index(op.f('ix_issue_activity_log_timestamp'), 'issue_activity_log', ['timestamp'], unique=False)
    op.create_table('issue_comments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('issue_id', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('comment_type', sa.String(), nullable=True),
    sa.Column('mentions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_by_name', sa.String(), nullable=True),
    sa.Column('created_by_role', sa.String(), nullable=True),
    sa.Column('timestamp', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['issue_id'], ['product_issues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pg_comments_issue_time', 'issue_comments', ['issue_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_issue_comments_created_by'), 'issue_comments', ['created_by'], unique=False)
    op.create_index(op.f('ix_issue_comments_issue_id'), 'issue_comments', ['issue_id'], unique=False)
    op.create_table('issue_duplicates_map',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('issue_id', sa.String(), nullable=False),
    sa.Column('duplicate_of', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('detected_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['duplicate_of'], ['product_issues.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['issue_id'], ['product_issues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pg_duplicates_pair', 'issue_duplicates_map', ['issue_id', 'duplicate_of'], unique=False)
    op.create_index(op.f('ix_issue_duplicates_map_duplicate_of'), 'issue_duplicates_map', ['duplicate_of'], unique=False)
    op.create_index(op.f('ix_issue_duplicates_map_issue_id'), 'issue_duplicates_map', ['issue_id'], unique=False)
    op.create_table('students',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('full_name_en', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('school_id', sa.String(), nullable=False),
    sa.Column('class_id', sa.String(), nullable=True),
    sa.Column('student_number', sa.String(), nullable=True),
    sa.Column('grade', sa.String(), nullable=True),
    sa.Column('date_of_birth', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('national_id', sa.String(), nullable=True),
    sa.Column('parent_phone', sa.String(), nullable=True),
    sa.Column('parent_email', sa.String(), nullable=True),
    sa.Column('parent_name', sa.String(), nullable=True),
    sa.Column('parent_id', sa.String(), nullable=True),
    sa.Column('qr_code', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_id'], ['parents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pg_students_number_school', 'students', ['student_number', 'school_id'], unique=False)
    op.create_index('idx_pg_students_school_active', 'students', ['school_id', 'is_active'], unique=False)
    op.create_index('idx_pg_students_school_class', 'students', ['school_id', 'class_id'], unique=False)
    op.create_index(op.f('ix_students_class_id'), 'students', ['class_id'], unique=False)
    op.create_index(op.f('ix_students_email'), 'students', ['email'], unique=False)
    op.create_index(op.f('ix_students_school_id'), 'students', ['school_id'], unique=False)
    op.create_table('teacher_assignments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('school_id', sa.String(), nullable=False),
    sa.Column('teacher_id', sa.String(), nullable=False),
    sa.Column('class_id', sa.String(), nullable=False),
    sa.Column('subject_id', sa.String(), nullable=False),
    sa.Column('weekly_sessions', sa.Integer(), nullable=True),
    sa.Column('periods_per_week', sa.Integer(), nullable=True),
    sa.Column('academic_year', sa.String(), nullable=True),
    sa.Column('semester', sa.Integer(), nullable=True),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('teacher_name', sa.String(), nullable=True),
    sa.Column('class_name', sa.String(), nullable=True),
    sa.Column('subject_name', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pg_assigns_school_class', 'teacher_assignments', ['school_id', 'class_id'], unique=False)
    op.create_index('idx_pg_assigns_school_teacher', 'teacher_assignments', ['school_id', 'teacher_id'], unique=False)
    op.create_index(op.f('ix_teacher_assignments_school_id'), 'teacher_assignments', ['school_id'], unique=False)
    op.create_index(op.f('ix_teacher_assignments_teacher_id'), 'teacher_assignments', ['teacher_id'], unique=False)
    op.create_table('teacher_class_assignments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('school_id', sa.String(), nullable=False),
    sa.Column('teacher_id', sa.String(), nullable=False),
    sa.Column('class_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'teacher_id', 'class_id', name='uq_tca_school_teacher_class')
    )
    op.create_table('teacher_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('school_id', sa.String(), nullable=False),
    sa.Column('teacher_id', sa.String(), nullable=False),
    sa.Column('class_id', sa.String(), nullable=True),
    sa.Column('subject_id', sa.String(), nullable=True),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('start_time', sa.String(), nullable=True),
    sa.Column('end_time', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('topic', sa.String(), nullable=True),
    sa.Column('objectives', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('attendance_taken', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pg_tsessions_class_date', 'teacher_sessions', ['class_id', 'date'], unique=False)
    op.create_index('idx_pg_tsessions_school_date', 'teacher_sessions', ['school_id', 'date'], unique=False)
    op.create_index('idx_pg_tsessions_teacher_date', 'teacher_sessions', ['teacher_id', 'date'], unique=False)
    op.create_index(op.f('ix_teacher_sessions_class_id'), 'teacher_sessions', ['class_id'], unique=False)
    op.create_index(op.f('ix_teacher_sessions_school_id'), 'teacher_sessions', ['school_id'], unique=False)
    op.create_index(op.f('ix_teacher_sessions_teacher_id'), 'teacher_sessions', ['teacher_id'], unique=False)
    op.create_table('ai_interventions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('school_id', sa.String(), nullable=True),
    sa.Column('student_id', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('approved_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pg_ai_interventions_school_status', 'ai_interventions', ['school_id', 'status'], unique=False)
    op.create_index('idx_pg_ai_interventions_student_status', 'ai_interventions', ['student_id', 'status'], unique=False)
    op.create_index(op.f('ix_ai_interventions_created_at'), 'ai_interventions', ['created_at'], unique=False)
    op.create_index(op.f('ix_ai_interventions_school_id'), 'ai_interventions', ['school_id'], unique=False)
    op.create_index(op.f('ix_ai_interventions_status'), 'ai_interventions', ['status'], unique=False)
    op.create_index(op.f('ix_ai_interventions_student_id'), 'ai_interventions', ['student_id'], unique=False)
    op.create_table('assessment_submissions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('assessment_id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('grade', sa.String(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('submitted_at', sa.String(), nullable=True),
    sa.Column('graded_at', sa.String(), nullable=True),
    sa.Column('graded_by', sa.String(), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['graded_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pg_submissions_assessment_student', 'assessment_submissions', ['assessment_id', 'student_id'], unique=False)
    op.create_index(op.f('ix_assessment_submissions_assessment_id'), 'assessment_submissions', ['assessment_id'], unique=False)
    op.create_index(op.f('ix_assessment_submissions_student_id'), 'assessment_submissions', ['student_id'], unique=False)
    op.create_table('attendance',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('school_id', sa.String(), nullable=False),
    sa.Column('class_id', sa.String(), nullable=True),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('recorded_by', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_excused', sa.Boolean(), nullable=True),
    sa.Column('excuse_reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pg_attendance_class_date', 'attendance', ['class_id', 'date'], unique=False)
    op.create_index('idx_pg_attendance_school_class_date', 'attendance', ['school_id', 'class_id', 'date'], unique=False)
    op.create_index('idx_pg_attendance_school_date', 'attendance', ['school_id', 'date'], unique=False)
    op.create_index('idx_pg_attendance_student_date', 'attendance', ['student_id', 'date'], unique=False)
    op.create_index(op.f('ix_attendance_class_id'), 'attendance', ['class_id'], unique=False)
    op.create_index(op.f('ix_attendance_school_id'), 'attendance', ['school_id'], unique=False)
    op.create_index(op.f('ix_attendance_student_id'), 'attendance', ['student_id'], unique=False)
    op.create_table('behaviour_records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('school_id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('class_id', sa.String(), nullable=True),
    sa.Column('teacher_id', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('action_taken', sa.Text(), nullable=True),
    sa.Column('parent_notified', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pg_behaviour_school_date', 'behaviour_records', ['school_id', 'date'], unique=False)
    op.create_index('idx_pg_behaviour_school_student', 'behaviour_records', ['school_id', 'student_id'], unique=False)
    op.create_index(op.f('ix_behaviour_records_school_id'), 'behaviour_records', ['school_id'], unique=False)
    op.create_index(op.f('ix_behaviour_records_student_id'), 'behaviour_records', ['student_id'], unique=False)
    op.create_table('schedule_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('school_id', sa.String(), nullable=False),
    sa.Column('schedule_id', sa.String(), nullable=False),
    sa.Column('assignment_id', sa.String(), nullable=True),
    sa.Column('teacher_id', sa.String(), nullable=True),
    sa.Column('class_id', sa.String(), nullable=True),
    sa.Column('subject_id', sa.String(), nullable=True),
    sa.Column('day_of_week', sa.String(), nullable=False),
    sa.Column('day', sa.String(), nullable=True),
    sa.Column('time_slot_id', sa.String(), nullable=True),
    sa.Column('slot_number', sa.Integer(), nullable=True),
    sa.Column('room_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('teacher_name', sa.String(), nullable=True),
    sa.Column('class_name', sa.String(), nullable=True),
    sa.Column('subject_name', sa.String(), nullable=True),
    sa.Column('time_slot_name', sa.String(), nullable=True),
    sa.Column('start_time', sa.String(), nullable=True),
    sa.Column('end_time', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['teacher_assignments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['time_slot_id'], ['time_slots.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pg_sessions_class_day', 'schedule_sessions', ['class_id', 'day_of_week'], unique=False)
    op.create_index('idx_pg_sessions_school_sched_day', 'schedule_sessions', ['school_id', 'schedule_id', 'day_of_week'], unique=False)
    op.create_index('idx_pg_sessions_teacher_day', 'schedule_sessions', ['teacher_id', 'day_of_week'], unique=False)
    op.create_index(op.f('ix_schedule_sessions_class_id'), 'schedule_sessions', ['class_id'], unique=False)
    op.create_index(op.f('ix_schedule_sessions_school_id'), 'schedule_sessions', ['school_id'], unique=False)
    op.create_index(op.f('ix_schedule_sessions_teacher_id'), 'schedule_sessions', ['teacher_id'], unique=False)
    op.create_table('session_interactions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('recorded_by', sa.String(), nullable=True),
    sa.Column('timestamp', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_interactions_session_id'), 'session_interactions', ['session_id'], unique=False)
    op.create_index(op.f('ix_session_interactions_student_id'), 'session_interactions', ['student_id'], unique=False)
    op.create_index(op.f('ix_session_interactions_type'), 'session_interactions', ['type'], unique=False)
    op.create_table('session_notes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('teacher_id', sa.String(), nullable=True),
    sa.Column('student_id', sa.String(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_notes_session_id'), 'session_notes', ['session_id'], unique=False)
    op.create_index(op.f('ix_session_notes_student_id'), 'session_notes', ['student_id'], unique=False)
    op.create_index(op.f('ix_session_notes_teacher_id'), 'session_notes', ['teacher_id'], unique=False)
    op.create_table('student_skills',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('skill_type_id', sa.String(), nullable=True),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('class_id', sa.String(), nullable=True),
    sa.Column('school_id', sa.String(), nullable=True),
    sa.Column('level', sa.String(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('assessed_by', sa.String(), nullable=True),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['assessed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_type_id'], ['skills_types.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_skills_class_id'), 'student_skills', ['class_id'], unique=False)
    op.create_index(op.f('ix_student_skills_session_id'), 'student_skills', ['session_id'], unique=False)
    op.create_index(op.f('ix_student_skills_skill_type_id'), 'student_skills', ['skill_type_id'], unique=False)
    op.create_index(op.f('ix_student_skills_student_id'), 'student_skills', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_skills_student_id'), table_name='student_skills')
    op.drop_index(op.f('ix_student_skills_skill_type_id'), table_name='student_skills')
    op.drop_index(op.f('ix_student_skills_session_id'), table_name='student_skills')
    op.drop_index(op.f('ix_student_skills_class_id'), table_name='student_skills')
    op.drop_table('student_skills')
    op.drop_index(op.f('ix_session_notes_teacher_id'), table_name='session_notes')
    op.drop_index(op.f('ix_session_notes_student_id'), table_name='session_notes')
    op.drop_index(op.f('ix_session_notes_session_id'), table_name='session_notes')
    op.drop_table('session_notes')
    op.drop_index(op.f('ix_session_interactions_type'), table_name='session_interactions')
    op.drop_index(op.f('ix_session_interactions_student_id'), table_name='session_interactions')
    op.drop_index(op.f('ix_session_interactions_session_id'), table_name='session_interactions')
    op.drop_table('session_interactions')
    op.drop_index(op.f('ix_schedule_sessions_teacher_id'), table_name='schedule_sessions')
    op.drop_index(op.f('ix_schedule_sessions_school_id'), table_name='schedule_sessions')
    op.drop_index(op.f('ix_schedule_sessions_class_id'), table_name='schedule_sessions')
    op.drop_index('idx_pg_sessions_teacher_day', table_name='schedule_sessions')
    op.drop_index('idx_pg_sessions_school_sched_day', table_name='schedule_sessions')
    op.drop_index('idx_pg_sessions_class_day', table_name='schedule_sessions')
    op.drop_table('schedule_sessions')
    op.drop_index(op.f('ix_behaviour_records_student_id'), table_name='behaviour_records')
    op.drop_index(op.f('ix_behaviour_records_school_id'), table_name='behaviour_records')
    op.drop_index('idx_pg_behaviour_school_student', table_name='behaviour_records')
    op.drop_index('idx_pg_behaviour_school_date', table_name='behaviour_records')
    op.drop_table('behaviour_records')
    op.drop_index(op.f('ix_attendance_student_id'), table_name='attendance')
    op.drop_index(op.f('ix_attendance_school_id'), table_name='attendance')
    op.drop_index(op.f('ix_attendance_class_id'), table_name='attendance')
    op.drop_index('idx_pg_attendance_student_date', table_name='attendance')
    op.drop_index('idx_pg_attendance_school_date', table_name='attendance')
    op.drop_index('idx_pg_attendance_school_class_date', table_name='attendance')
    op.drop_index('idx_pg_attendance_class_date', table_name='attendance')
    op.drop_table('attendance')
    op.drop_index(op.f('ix_assessment_submissions_student_id'), table_name='assessment_submissions')
    op.drop_index(op.f('ix_assessment_submissions_assessment_id'), table_name='assessment_submissions')
    op.drop_index('idx_pg_submissions_assessment_student', table_name='assessment_submissions')
    op.drop_table('assessment_submissions')
    op.drop_index(op.f('ix_ai_interventions_student_id'), table_name='ai_interventions')
    op.drop_index(op.f('ix_ai_interventions_status'), table_name='ai_interventions')
    op.drop_index(op.f('ix_ai_interventions_school_id'), table_name='ai_interventions')
    op.drop_index(op.f('ix_ai_interventions_created_at'), table_name='ai_interventions')
    op.drop_index('idx_pg_ai_interventions_student_status', table_name='ai_interventions')
    op.drop_index('idx_pg_ai_interventions_school_status', table_name='ai_interventions')
    op.drop_table('ai_interventions')
    op.drop_index(op.f('ix_teacher_sessions_teacher_id'), table_name='teacher_sessions')
    op.drop_index(op.f('ix_teacher_sessions_school_id'), table_name='teacher_sessions')
    op.drop_index(op.f('ix_teacher_sessions_class_id'), table_name='teacher_sessions')
    op.drop_index('idx_pg_tsessions_teacher_date', table_name='teacher_sessions')
    op.drop_index('idx_pg_tsessions_school_date', table_name='teacher_sessions')
    op.drop_index('idx_pg_tsessions_class_date', table_name='teacher_sessions')
    op.drop_table('teacher_sessions')
    op.drop_table('teacher_class_assignments')
    op.drop_index(op.f('ix_teacher_assignments_teacher_id'), table_name='teacher_assignments')
    op.drop_index(op.f('ix_teacher_assignments_school_id'), table_name='teacher_assignments')
    op.drop_index('idx_pg_assigns_school_teacher', table_name='teacher_assignments')
    op.drop_index('idx_pg_assigns_school_class', table_name='teacher_assignments')
    op.drop_table('teacher_assignments')
    op.drop_index(op.f('ix_students_school_id'), table_name='students')
    op.drop_index(op.f('ix_students_email'), table_name='students')
    op.drop_index(op.f('ix_students_class_id'), table_name='students')
    op.drop_index('idx_pg_students_school_class', table_name='students')
    op.drop_index('idx_pg_students_school_active', table_name='students')
    op.drop_index('idx_pg_students_number_school', table_name='students')
    op.drop_table('students')
    op.drop_index(op.f('ix_issue_duplicates_map_issue_id'), table_name='issue_duplicates_map')
    op.drop_index(op.f('ix_issue_duplicates_map_duplicate_of'), table_name='issue_duplicates_map')
    op.drop_index('idx_pg_duplicates_pair', table_name='issue_duplicates_map')
    op.drop_table('issue_duplicates_map')
    op.drop_index(op.f('ix_issue_comments_issue_id'), table_name='issue_comments')
    op.drop_index(op.f('ix_issue_comments_created_by'), table_name='issue_comments')
    op.drop_index('idx_pg_comments_issue_time', table_name='issue_comments')
    op.drop_table('issue_comments')
    op.drop_index(op.f('ix_issue_activity_log_timestamp'), table_name='issue_activity_log')
    op.drop_index(op.f('ix_issue_activity_log_performed_by'), table_name='issue_activity_log')
    op.drop_index(op.f('ix_issue_activity_log_issue_id'), table_name='issue_activity_log')
    op.drop_index(op.f('ix_issue_activity_log_action'), table_name='issue_activity_log')
    op.drop_index('idx_pg_activity_issue_time', table_name='issue_activity_log')
    op.drop_table('issue_activity_log')
    op.drop_index(op.f('ix_assessments_teacher_id'), table_name='assessments')
    op.drop_index(op.f('ix_assessments_school_id'), table_name='assessments')
    op.drop_index(op.f('ix_assessments_class_id'), table_name='assessments')
    op.drop_index('idx_pg_assessments_school_class', table_name='assessments')
    op.drop_table('assessments')
    op.drop_index(op.f('ix_approval_events_request_id'), table_name='approval_events')
    op.drop_index('idx_pg_approval_events_request', table_name='approval_events')
    op.drop_table('approval_events')
    op.drop_index(op.f('ix_session_event_log_session_id'), table_name='session_event_log')
    op.drop_index(op.f('ix_session_event_log_event_type'), table_name='session_event_log')
    op.drop_index('idx_pg_session_events_session_time', table_name='session_event_log')
    op.drop_table('session_event_log')
    op.drop_index(op.f('ix_registration_requests_status'), table_name='registration_requests')
    op.drop_index('idx_pg_requests_status_date', table_name='registration_requests')
    op.drop_table('registration_requests')
    op.drop_index(op.f('ix_product_issues_status'), table_name='product_issues')
    op.drop_index(op.f('ix_product_issues_section'), table_name='product_issues')
    op.drop_index(op.f('ix_product_issues_priority'), table_name='product_issues')
    op.drop_index(op.f('ix_product_issues_issue_type'), table_name='product_issues')
    op.drop_index(op.f('ix_product_issues_is_deleted'), table_name='product_issues')
    op.drop_index(op.f('ix_product_issues_employee_name'), table_name='product_issues')
    op.drop_index(op.f('ix_product_issues_created_by'), table_name='product_issues')
    op.drop_index(op.f('ix_product_issues_assigned_team'), table_name='product_issues')
    op.drop_index('idx_pg_issues_status_team', table_name='product_issues')
    op.drop_index('idx_pg_issues_status_priority_date', table_name='product_issues')
    op.drop_index('idx_pg_issues_created_by_date', table_name='product_issues')
    op.drop_index('idx_pg_issues_active_status_date', table_name='product_issues')
    op.drop_index('idx_pg_issues_active_creator_date', table_name='product_issues')
    op.drop_table('product_issues')
    op.drop_index(op.f('ix_platform_settings_type'), table_name='platform_settings')
    op.drop_table('platform_settings')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_tenant_id'), table_name='notifications')
    op.drop_index('idx_pg_notifications_user_read_date', table_name='notifications')
    op.drop_index('idx_pg_notifications_tenant_date', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_messages_sender_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_recipient_id'), table_name='messages')
    op.drop_index('idx_pg_messages_sender', table_name='messages')
    op.drop_index('idx_pg_messages_recipient', table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_classes_school_id'), table_name='classes')
    op.drop_index('idx_pg_classes_school_grade', table_name='classes')
    op.drop_index('idx_pg_classes_school_active', table_name='classes')
    op.drop_table('classes')
    op.drop_index(op.f('ix_bulk_action_history_performed_at'), table_name='bulk_action_history')
    op.drop_index('idx_pg_bulk_history_user_date', table_name='bulk_action_history')
    op.drop_table('bulk_action_history')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_school_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_performed_by'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_index('idx_pg_audit_user_time', table_name='audit_logs')
    op.drop_index('idx_pg_audit_school_time', table_name='audit_logs')
    op.drop_index('idx_pg_audit_entity', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_table('approval_requests')
    op.drop_index(op.f('ix_academic_terms_school_id'), table_name='academic_terms')
    op.drop_index('idx_pg_terms_school_year', table_name='academic_terms')
    op.drop_table('academic_terms')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index('idx_pg_users_tenant_active', table_name='users')
    op.drop_index('idx_pg_users_role_tenant', table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_timetables_school_id'), table_name='timetables')
    op.drop_table('timetables')
    op.drop_index(op.f('ix_timetable_runs_school_id'), table_name='timetable_runs')
    op.drop_table('timetable_runs')
    op.drop_table('timetable_constraints')
    op.drop_index(op.f('ix_time_slots_school_id'), table_name='time_slots')
    op.drop_table('time_slots')
    op.drop_index(op.f('ix_teachers_school_id'), table_name='teachers')
    op.drop_index(op.f('ix_teachers_email'), table_name='teachers')
    op.drop_index('idx_pg_teachers_school_active', table_name='teachers')
    op.drop_table('teachers')
    op.drop_index(op.f('ix_subjects_school_id'), table_name='subjects')
    op.drop_table('subjects')
    op.drop_index(op.f('ix_school_settings_school_id'), table_name='school_settings')
    op.drop_table('school_settings')
    op.drop_table('physical_classrooms')
    op.drop_index(op.f('ix_parents_email'), table_name='parents')
    op.drop_table('parents')
    op.drop_index(op.f('ix_lookup_options_category'), table_name='lookup_options')
    op.drop_index('idx_pg_lookup_category_key', table_name='lookup_options')
    op.drop_table('lookup_options')
    op.drop_index(op.f('ix_hakim_insights_school_id'), table_name='hakim_insights')
    op.drop_index('idx_pg_hakim_school_date', table_name='hakim_insights')
    op.drop_table('hakim_insights')
    op.drop_table('grade_levels')
    op.drop_table('behaviour_types')
    op.drop_index(op.f('ix_ai_insights_school_id'), table_name='ai_insights')
    op.drop_index(op.f('ix_ai_insights_insight_type'), table_name='ai_insights')
    op.drop_index(op.f('ix_ai_insights_entity_type'), table_name='ai_insights')
    op.drop_index(op.f('ix_ai_insights_created_at'), table_name='ai_insights')
    op.drop_index('idx_pg_ai_insights_school_type', table_name='ai_insights')
    op.drop_index('idx_pg_ai_insights_entity_type', table_name='ai_insights')
    op.drop_table('ai_insights')
    op.drop_index(op.f('ix_academic_years_school_id'), table_name='academic_years')
    op.drop_table('academic_years')
    op.drop_index(op.f('ix_skills_types_category'), table_name='skills_types')
    op.drop_table('skills_types')
    op.drop_index(op.f('ix_schools_status'), table_name='schools')
    op.drop_index(op.f('ix_schools_code'), table_name='schools')
    op.drop_index(op.f('ix_schools_city'), table_name='schools')
    op.drop_table('schools')
    op.drop_table('educational_stages')
    op.drop_table('counters')
    # ### end Alembic commands ###
