"""add_device_info_severity_to_audit_logs

Revision ID: b9e08d69a15a
Revises: f3a1b2c4d5e6
Create Date: 2026-04-05 18:29:42.648644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b9e08d69a15a'
down_revision: Union[str, Sequence[str], None] = 'f3a1b2c4d5e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('severity', sa.String(), nullable=True))
    op.add_column('audit_logs', sa.Column('actor_email', sa.String(), nullable=True))
    op.add_column('audit_logs', sa.Column('target_name', sa.String(), nullable=True))
    op.add_column('audit_logs', sa.Column('device_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('audit_logs', sa.Column('status', sa.String(), nullable=True))
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_severity'), 'audit_logs', ['severity'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_logs_severity'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_column('audit_logs', 'status')
    op.drop_column('audit_logs', 'device_info')
    op.drop_column('audit_logs', 'target_name')
    op.drop_column('audit_logs', 'actor_email')
    op.drop_column('audit_logs', 'severity')
    # ### end Alembic commands ###
