// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/schedule-grid/CellModal.tsx": () => import("../components/mockups/schedule-grid/CellModal.tsx"),
  "./components/mockups/schedule-grid/MasterGrid.tsx": () => import("../components/mockups/schedule-grid/MasterGrid.tsx")
};
