import React from 'react';
import {
  Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription, DialogFooter,
} from '@/shared/components/ui/dialog';
import { Button } from '@/shared/components/ui/button';
import { Input } from '@/shared/components/ui/input';
import { Label } from '@/shared/components/ui/label';
import { Key, Mail, Lock, Sparkles, Eye, EyeOff, Loader2, Save } from 'lucide-react';

export default function SchoolCredentialsDialog({
  open,
  onOpenChange,
  hasCredentials,
  credForm,
  setCredForm,
  showPassword,
  setShowPassword,
  onGeneratePassword,
  onSaveCredentials,
  credLoading,
  isRTL,
  t,
}) {
  return (
    <Dialog
      open={open}
      onOpenChange={(o) => {
        onOpenChange(o);
        if (!o) setShowPassword(false);
      }}
    >
      <DialogContent className="max-w-lg rounded-3xl bg-white dark:bg-slate-900 border-slate-200 dark:border-slate-800 shadow-2xl p-6 font-cairo">
        <DialogHeader>
          <DialogTitle className="font-cairo text-lg font-black flex items-center gap-2 text-[#1C3D74] dark:text-[#46C1BE]">
            <Key className="h-5 w-5" />
            <span>
              {hasCredentials
                ? (t('updateSchoolLoginCredentials') || (isRTL ? 'تحديث بيانات تسجيل الدخول' : 'Update Credentials'))
                : (t('createSchoolPrincipalAccount') || (isRTL ? 'إنشاء حساب مدير المدرسة' : 'Create Principal Account'))
              }
            </span>
          </DialogTitle>
          <DialogDescription className="text-xs font-semibold text-slate-500 dark:text-slate-400 mt-1">
            {hasCredentials
              ? (t('updateTheEmailAndorPasswordForTheSchoolPrincipalAc') || (isRTL ? 'قم بتحديث البريد الإلكتروني أو كلمة المرور لحساب مدير المدرسة' : 'Update the email and/or password for the school principal account'))
              : (t('createANewAccountForTheSchoolPrincipalToAccessTheS') || (isRTL ? 'إنشاء حساب رسمي لمدير المدرسة لتمكينه من دخول لوحة التحكم' : 'Create a new account for the school principal to access the system'))
            }
          </DialogDescription>
        </DialogHeader>

        <div className="space-y-4 py-3">
          {/* Email */}
          <div className="space-y-1.5">
            <Label className="text-xs font-bold text-slate-800 dark:text-slate-200">
              {isRTL ? 'البريد الإلكتروني' : 'Email Address'} <span className="text-rose-500">*</span>
            </Label>
            <div className="relative">
              <Mail className={`absolute ${isRTL ? 'right-3' : 'left-3'} top-1/2 -translate-y-1/2 h-4 w-4 text-slate-400`} />
              <Input
                type="email"
                dir="ltr"
                placeholder="principal@school.edu.sa"
                value={credForm.email}
                onChange={(e) => setCredForm(f => ({ ...f, email: e.target.value }))}
                className={`${isRTL ? 'pr-9.5' : 'pl-9.5'} h-11 rounded-xl font-mono text-xs bg-slate-50 dark:bg-slate-950 border-slate-300 dark:border-slate-700`}
              />
            </div>
          </div>

          {/* Full Name */}
          <div className="space-y-1.5">
            <Label className="text-xs font-bold text-slate-800 dark:text-slate-200">
              {t('fullName') || (isRTL ? 'اسم مدير المدرسة' : 'Principal Full Name')}
            </Label>
            <Input
              placeholder={t('principalFullName') || (isRTL ? 'الاسم الثلاثي لمدير المدرسة' : 'Principal full name')}
              value={credForm.name}
              onChange={(e) => setCredForm(f => ({ ...f, name: e.target.value }))}
              className="h-11 rounded-xl text-xs bg-slate-50 dark:bg-slate-950 border-slate-300 dark:border-slate-700"
            />
          </div>

          {/* Password with generator */}
          <div className="space-y-1.5">
            <div className="flex items-center justify-between">
              <Label className="text-xs font-bold text-slate-800 dark:text-slate-200">
                {hasCredentials
                  ? (t('newPasswordLeaveBlankToKeepCurrent') || (isRTL ? 'كلمة المرور الجديدة (اتركها فارغة للإبقاء)' : 'New Password (leave blank to keep current)'))
                  : (t('password') || (isRTL ? 'كلمة المرور' : 'Password'))
                }
                {!hasCredentials && (
                  <span className="text-slate-400 font-normal ms-1">
                    ({t('autogeneratedIfBlank') || (isRTL ? 'توليد تلقائي إن تركت فارغة' : 'autogenerated if blank')})
                  </span>
                )}
              </Label>
              <button
                type="button"
                onClick={onGeneratePassword}
                className="text-xs font-bold text-[#46C1BE] hover:underline flex items-center gap-1"
              >
                <Sparkles className="h-3.5 w-3.5" />
                <span>{t('generate') || (isRTL ? 'توليد كلمة سر' : 'Generate')}</span>
              </button>
            </div>
            <div className="relative">
              <Lock className={`absolute ${isRTL ? 'right-3' : 'left-3'} top-1/2 -translate-y-1/2 h-4 w-4 text-slate-400`} />
              <Input
                type={showPassword ? 'text' : 'password'}
                dir="ltr"
                placeholder={isRTL ? '••••••••••••' : '••••••••••••'}
                value={credForm.password}
                onChange={(e) => setCredForm(f => ({ ...f, password: e.target.value }))}
                className={`${isRTL ? 'pr-9.5 pl-10' : 'pl-9.5 pr-10'} h-11 rounded-xl font-mono text-xs tracking-wider bg-slate-50 dark:bg-slate-950 border-slate-300 dark:border-slate-700`}
              />
              <button
                type="button"
                onClick={() => setShowPassword(s => !s)}
                className={`absolute ${isRTL ? 'left-3' : 'right-3'} top-1/2 -translate-y-1/2 text-slate-400 hover:text-slate-600`}
              >
                {showPassword ? <EyeOff className="h-4 w-4" /> : <Eye className="h-4 w-4" />}
              </button>
            </div>
          </div>

          {/* Confirm Password (only if entered) */}
          {credForm.password && (
            <div className="space-y-1.5 animate-in fade-in-30 duration-200">
              <Label className="text-xs font-bold text-slate-800 dark:text-slate-200">
                {t('confirmPassword') || (isRTL ? 'تأكيد كلمة المرور' : 'Confirm Password')} <span className="text-rose-500">*</span>
              </Label>
              <Input
                type={showPassword ? 'text' : 'password'}
                dir="ltr"
                placeholder={t('reenterPassword') || (isRTL ? 'أعد إدخال كلمة المرور' : 'Re-enter password')}
                value={credForm.confirmPassword}
                onChange={(e) => setCredForm(f => ({ ...f, confirmPassword: e.target.value }))}
                className={`h-11 rounded-xl font-mono text-xs tracking-wider bg-slate-50 dark:bg-slate-950 ${
                  credForm.password && credForm.confirmPassword && credForm.password !== credForm.confirmPassword
                    ? 'border-rose-400 focus:ring-rose-300'
                    : 'border-slate-300 dark:border-slate-700'
                }`}
              />
              {credForm.password && credForm.confirmPassword && credForm.password !== credForm.confirmPassword && (
                <p className="text-xs text-rose-500 font-bold">{t('passwordsDoNotMatch') || (isRTL ? 'كلمات المرور غير متطابقة' : 'Passwords do not match')}</p>
              )}
            </div>
          )}
        </div>

        <DialogFooter className="gap-2 sm:gap-2">
          <Button
            variant="outline"
            onClick={() => onOpenChange(false)}
            disabled={credLoading}
            className="rounded-xl text-xs font-bold border-slate-300 dark:border-slate-700"
          >
            {t('cancel') || (isRTL ? 'إلغاء' : 'Cancel')}
          </Button>
          <Button
            onClick={onSaveCredentials}
            disabled={credLoading || !credForm.email || (credForm.password && credForm.password !== credForm.confirmPassword)}
            className="rounded-xl text-xs font-extrabold bg-[#1C3D74] hover:bg-[#152e57] text-white shadow-md shadow-[#1C3D74]/20 gap-1.5"
          >
            {credLoading ? <Loader2 className="h-4 w-4 animate-spin" /> : <Save className="h-4 w-4" />}
            <span>{hasCredentials ? (isRTL ? 'تحديث البيانات' : 'Update') : (t('createAccount') || (isRTL ? 'إنشاء الحساب' : 'Create Account'))}</span>
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
