import React from 'react';
import { FileText, School } from 'lucide-react';
import { REQUEST_STATUSES } from './constants';

export const APPROVAL_TYPE_CONFIG = {
  teacher: {
    tabValue: 'requests',
    // A queued `teacher` request is a SCHOOL teacher joining an existing school.
    // Independent Teachers are auto-approved at signup and never reach this queue.
    tabLabel: 'طلبات معلمي المدارس',
    tabIcon: FileText,
    cardTitle: 'طلبات تسجيل معلمي المدارس',
    emptyTitle: 'لا توجد طلبات',
    emptyMessage: 'لا توجد طلبات تسجيل معلمي مدارس حالياً',
    avatarBg: 'bg-cyan-500',
    avatarContent: (r) => r.full_name?.charAt(0),
    nameField: 'full_name',
    approveTitle: 'تأكيد الموافقة على طلب إنشاء حساب',
    approveDesc: 'هل أنت متأكد من الموافقة على طلب إنشاء حساب لهذا المعلم؟',
    approveNote: 'سيتم إنشاء حساب للمعلم وربطه بالمدرسة المختارة وتوليد بيانات الدخول و QR Code',
    successTitle: 'تم إنشاء الحساب بنجاح!',
    successSubtitle: 'بيانات الحساب الجديد:',
    rejectTitle: (r) => `رفض طلب ${r?.full_name || ''}`,
    quickReasons: ['بيانات غير مكتملة', 'بيانات غير صحيحة', 'حساب مكرر', 'المعلم غير مؤهل'],
    showMoreInfoAction: true,
    statusFilters: REQUEST_STATUSES,
    confirmFields: (r) => [
      { label: 'الاسم', value: r.full_name },
      { label: 'البريد', value: r.email, dir: 'ltr' },
      { label: 'الهاتف', value: r.phone, dir: 'ltr' },
      r.subject && { label: 'المادة', value: r.subject },
      r.educational_level && { label: 'المرحلة', value: r.educational_level },
      r.school_mentioned && { label: 'المدرسة', value: r.school_mentioned },
      r.school_code && { label: 'رمز المدرسة المُدخل', value: r.school_code, dir: 'ltr' },
    ].filter(Boolean),
    cardFields: (r) => [
      { label: 'رقم الهوية', value: r.national_id, dir: 'ltr' },
      { label: 'الهاتف', value: r.phone, dir: 'ltr' },
      { label: 'المادة', value: r.subject },
      { label: 'المرحلة', value: r.education_level || r.educational_level },
      { label: 'البريد', value: r.email, dir: 'ltr', colSpan: 2 },
      r.school_mentioned && { label: 'المدرسة المذكورة', value: r.school_mentioned, colSpan: 2 },
      r.school_code && { label: 'رمز المدرسة المُدخل', value: r.school_code, dir: 'ltr' },
      { label: 'تاريخ الطلب', value: '__date__', dateKey: 'created_at' },
      r.rejection_reason && { label: 'سبب الرفض', value: r.rejection_reason, colSpan: 2, className: 'text-red-600' },
    ].filter(Boolean),
    credentialFields: (data) => [
      data.credentials?.teacher_id && { label: 'رقم المعلم', value: data.credentials.teacher_id },
      { label: 'البريد', value: data.credentials?.email || data.email, dir: 'ltr' },
      { label: 'كلمة المرور', value: data.credentials?.temporary_password || data.temporary_password, highlight: true },
    ].filter(Boolean),
    showQrCode: true,
  },
  school: {
    tabValue: 'school-requests',
    tabLabel: 'طلبات المدارس',
    tabIcon: School,
    cardTitle: 'طلبات تسجيل المدارس',
    emptyTitle: 'لا توجد طلبات',
    emptyMessage: 'لا توجد طلبات تسجيل مدارس حالياً',
    avatarBg: 'bg-teal-500',
    avatarContent: () => <School className="h-6 w-6" />,
    nameField: 'school_name',
    approveTitle: 'تأكيد الموافقة على طلب تسجيل المدرسة',
    approveDesc: 'سيتم إنشاء المدرسة وحساب المدير — هل أنت متأكد؟',
    approveNote: 'سيتم إنشاء المدرسة وحساب المدير وتوليد بيانات الدخول المؤقتة',
    successTitle: 'تم إنشاء المدرسة بنجاح!',
    successSubtitle: 'بيانات المدرسة والمدير:',
    rejectTitle: (r) => `رفض طلب مدرسة ${r?.school_name || ''}`,
    quickReasons: ['بيانات المدرسة غير مكتملة', 'المدرسة مسجلة مسبقاً', 'بيانات المدير غير صحيحة'],
    showMoreInfoAction: false,
    statusFilters: REQUEST_STATUSES,
    confirmFields: (r) => [
      { label: 'اسم المدرسة', value: r.school_name },
      { label: 'مدير المدرسة', value: r.full_name },
      { label: 'البريد', value: r.school_email || r.email, dir: 'ltr' },
      { label: 'الهاتف', value: r.school_phone || r.phone, dir: 'ltr' },
      r.school_city && { label: 'المدينة', value: r.school_city },
    ].filter(Boolean),
    cardFields: (r) => [
      { label: 'مدير المدرسة', value: r.full_name },
      { label: 'البريد', value: r.school_email || r.email, dir: 'ltr' },
      { label: 'الهاتف', value: r.school_phone || r.phone, dir: 'ltr' },
      { label: 'المدينة', value: r.school_city || '-' },
      r.school_address && { label: 'العنوان', value: r.school_address, colSpan: 2 },
      { label: 'تاريخ الطلب', value: '__date__', dateKey: 'created_at' },
      r.school_code && { label: 'رمز المدرسة', value: r.school_code, className: 'font-mono font-bold text-brand-navy' },
      r.rejection_reason && { label: 'سبب الرفض', value: r.rejection_reason, colSpan: 2, className: 'text-red-600' },
    ].filter(Boolean),
    credentialFields: (data) => [
      data.credentials?.school_code && { label: 'رمز المدرسة', value: data.credentials.school_code, highlight: true },
      { label: 'البريد', value: data.credentials?.email || data.email, dir: 'ltr' },
      { label: 'كلمة المرور', value: data.credentials?.temporary_password || data.temporary_password, highlight: true },
    ].filter(Boolean),
    showQrCode: false,
  },
};
